CREATE TABLE TBL_PRODUCTS(
	ID NUMBER(10) NOT NULL,
	CATEGORY VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(100) NOT NULL,
	STOCK NUMBER(3) NOT NULL,
    PRICE NUMBER(5,2),
	CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE products_seq
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1;